### ISSUE TITLE
Also import user specified desktop files

### ISSUE THREAD

**Issue by ggof** [alamminsalo/qml-launcher#5]
Hi! 

 Is this project still supported? if so, I would like to contribute by adding this specific feature. At the moment, only desktop files located in `/usr/share/applications` are loaded, but some user-specific applications also have desktop files located at `$HOME/.local/share/applications`. 

I've already successfully implemented this on my system, and would like to know if there was any interest in me opening a PR for it? The modifications are of course very simple, less than 10 lines of code were changed. 

If this is of any interest, I'd be glad to open a pull request for it, as i think this launcher has a very nice finish.

**Comment by dev-0x7C6** [comment]
@ggof I addressed your issue in #6.
